#pragma once

#define IOCTL_READ_ULONG CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_WRITE_ULONG CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_READ_USHORT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_WRITE_USHORT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_READ_UCHAR CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_WRITE_UCHAR CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

typedef struct _WRITE_ULONG {
    PULONG addr;
    ULONG data;
} WRITE_ULONG;

typedef struct _READ_ULONG_ADDR {
    PULONG addr;
} READ_ULONG_ADDR;

typedef struct _READ_ULONG_DATA {
    ULONG data;
} READ_ULONG_DATA;

typedef struct _WRITE_USHORT {
    PUSHORT addr;
    USHORT data;
} WRITE_USHORT;

typedef struct _READ_USHORT_ADDR {
    PUSHORT addr;
} READ_USHORT_ADDR;

typedef struct _READ_USHORT_DATA {
    USHORT data;
} READ_USHORT_DATA;

typedef struct _WRITE_UCHAR {
    PUCHAR addr;
    UCHAR data;
} WRITE_UCHAR;

typedef struct _READ_UCHAR_ADDR {
    PUCHAR addr;
} READ_UCHAR_ADDR;

typedef struct _READ_UCHAR_DATA {
    UCHAR data;
} READ_UCHAR_DATA;
